### ISSUE TITLE
AWPer hand invisible

### ISSUE THREAD

**Issue by SpectrumVoid** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#10]
I downloaded the latest release (not the master) and the AWPer hand's model just didn't render. All the other sniper rifles I tested worked fine. Any idea what's wrong?
Using mastercomfig ultra

**Comment by agrastiOs** [comment]
Is it invisible on sv_pure 0 servers?

**Comment by SpectrumVoid** [comment]
It's hard to tell. It's just that now and then it's invisible. Most of the time it's completely visible.

**Comment by agrastiOs** [comment]
Seems like a bug related to sv_pure systems which would require Valve intervention, please reopen if there's evidence pointing otherwise.
