### ISSUE TITLE
Pyrovision Thermal Thruster taunt leaves behind particles after the taunt ends

### ISSUE THREAD

**Issue by FlaminSarge** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#12]
Unfortunately, I think this is due to how it reuses rainblower particles, but taunting with the Thermal Thruster in Pyrovision leaves these behind for what seems to be indefinitely:
![image](https://user-images.githubusercontent.com/2764675/82913011-9eca8b80-9f22-11ea-930d-c2d442e9e787.png)

These potentially need a max-life so that they fizzle out on their own.

I've verified this does not happen with stock particles (I can test individually with Rainblower vs other particle files, if necessary).

**Comment by agrastiOs** [comment]
That would be nice if you could test that, thanks.

**Comment by FlaminSarge** [comment]
It's definitely the flamethrower.pcf particles, just tested with solely that file. Gonna open up in Tools to see what needs changing, if I can.

**Comment by FlaminSarge** [comment]
Alright, quick fix for this:
On "taunt_pyro_gasblast_rainbow", under 'children', remove 'flamethrower_drips_rainbow'

This should keep the behavior of the rainbow flamethrower while not breaking the Thermal Thruster taunt.

If you still want drips on the taunt, I'm not quite sure how to fix it, as setting the effect duration for drips affects the rainbow flamethrower as well.

**Comment by FlaminSarge** [comment]
@agrastiOs Any other questions about this? I've fixed it for myself with the above changes so hopefully the attached pcf is all you need.

**Comment by NonhumanFromSteam** [comment]
Fixed

**Comment by agrastiOs** [comment]
@FlaminSarge Thank you for the help!

**Comment by FlaminSarge** [comment]
For quick reference, closed by https://github.com/agrastiOs/Ultimate-TF2-Visual-Fix-Pack/commit/8ab10550a3c59cb637bcdef2c4a7c0e814c8548e
