### ISSUE TITLE
Many fixed items render invisible when preloaded in Valve servers

### ISSUE THREAD

**Issue by TheThunderGuyS** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#14]
When I join a local game with sv_pure 0, the mod works as expected. However if I preload and then join casual, all items that have been fixed become invisible (hands are still seen however). A few examples below:

Backscatter:
![Image 1 - Backscatter](https://steamuserimages-a.akamaihd.net/ugc/1470939839001392346/50D23560545768D8DAC8D6735D2D5108B1E90E55/)

Direct Hit (being inspected)
![Image 2 - Direct Hit](https://steamuserimages-a.akamaihd.net/ugc/1470939839001395629/044DA9C5702FFDE64D34A7F4FCD47B7230337234/)

Sniper Rifle
![Image 3 - Sniper Rifle](https://steamuserimages-a.akamaihd.net/ugc/1470939839001397056/61B373A7CCECE9CBC00107E6923A5F35AEA69251/)

The Jag
![Image 4 - Jaggy :)](https://steamuserimages-a.akamaihd.net/ugc/1470939839001400816/41321D05186C894D5A1FF23C36418FB2BD4675A6/)

I don't know what is causing this. I have no configs and the only other mods are my self-made HUD, Carlzalph's Reduced Particles Mod and the No Bullet Dust script. It is likely the process of joining a sv_pure 1 server causing this.

**Comment by agrastiOs** [comment]
Taking all the reports in the account, it seems the sv_pure method of blocking model edits seems to be a bit broken. I'd suggest you shoot up an email to a TF Team dev detailing this issue if you would like to have it fixed. His email: eric s @valvesoftware.com (remove the spaces)

**Comment by TheThunderGuyS** [comment]
Closed as it is unrelated to the mod itself.
