### ISSUE TITLE
Better Dragons Fury Fix?

### ISSUE THREAD

**Issue by AtomicTEM** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#20]
Is this better than the current fix?

https://gamebanana.com/gamefiles/12945

**Comment by agrastiOs** [comment]
It is not.
In the comment where the uploader responded to your mention of our version, he said a few false claims:

The fix pack version does work with mat_phong 0.

Also, I'd like to note that the claim that these particles work on sv_pure 1 is incorrect. The creator of the particles that the uploader put in Gamebanana couldn't get them working in Casual as well: https://www.reddit.com/r/truetf2/comments/bfm2mx/dragons_fury_lag_fix/elgxy6o/?utm_source=reddit&utm_medium=web2x&context=3 It is sadly impossible to use custom particles in Valve servers. I have just tested the mod on Casual, and it does not work.

The fix pack version particle actually does have the optimizations of cutting the sprite count.
