### ISSUE TITLE
Dragon's Fury crashes my entire PC.

### ISSUE THREAD

**Issue by OrangeBandito** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#21]
Whenever I shoot the Dragon's Fury my computer shuts off and restarts immediately. I have no clue if this is on my end or if there's a problem with the particle or whatever.

**Comment by agrastiOs** [comment]
It seems highly unlikely that happens because of the particle. Can you confirm it happens with the particle removed out of the pack?

**Comment by agrastiOs** [comment]
Definitely seems to be on your end. Closing for now, the issue can be re-opened if you do confirm it doesn't happen if the particle is removed from the pack.
