### ISSUE TITLE
[request] Spy's sapper

### ISSUE THREAD

**Issue by MikhailaTF** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#23]
Spy's sapper used to drop a broken model when destroyed and no longer does so. I was wondering if it was possible to re-implement this. As per Team Comtress 2 #244 (https://github.com/mastercomfig/team-comtress-2/issues/244) they decided this issue is "too borderline" for them to take a stance on. However after a little digging I found that valve, as per update on March 12 2013 (https://wiki.teamfortress.com/wiki/March_12,_2013_Patch) converted the sapper to use the c_model system. If i recall it was this conversion that caused various issues with other stock weapons already fixed by this pack, so I wonder if this could've been the root of this issue as well?
On a side-note, I don't recall there being broken models for the Ap-Sap, the Snack Attack or the Red Tape Recorder (not sure about this last one) so I'm uncertain how this would work if the above issue would be fixed.
Anyway I took note of the integration into TC2 and plans for a part 2 of this pack, keep it up, you are doing god's work here!

**Comment by agrastiOs** [comment]
The gibs give metal, which affects balance. Impossible to fix as a client-side mod, and also shouldn't fix as removal of metal from sappers was probably intended.
