### ISSUE TITLE
sv_pure?

### ISSUE THREAD

**Issue by kamild1996** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#3]
Not necessarily an issue, just a question.
How's this fix pack handling servers with sv_pure, like casual servers?

**Comment by agrastiOs** [comment]
Doesn't work with sv_pure sadly, though sometimes some parts get through, also, rarely there's missing models in sv_pure servers, but rarely.

**Comment by agrastiOs** [comment]
@kamild1996 If you have any more related questions, please reopen
