### ISSUE TITLE
mat_picmip lower than -1

### ISSUE THREAD

**Issue by Platina6978** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#32]
I was considering asking this over on [TC2](https://github.com/mastercomfig/team-comtress-2) but as per their [issue #51](https://github.com/mastercomfig/team-comtress-2/issues/51) I think it better fits here instead.
Comments left there by people that I assume have much more knowledge when it comes to these kinds of things than I suggest that it would be better to achieve lower levels of mat_picmip by "cleaning up the assets" rather than allowing the game's code to set it to such a value (again). I myself have no clue what "cleaning up the assets" actually means in this particular case however.

**Comment by agrastiOs** [comment]
We actually do have plans to look into this!

Yep, by "cleaning up the assets", we are planning to fix some mipmap offsets for several textures.

**Comment by Ashetf2** [comment]
mat_picmip now can go lower than -1 so i guess you can close this issue.

**Comment by MikhailaTF** [comment]
> mat_picmip now can go lower than -1 so i guess you can close this issue.

Depends, does being allowed to set mat_picmip below -1 also imply that the textures are indeed "cleaned" as proposed above, or did they simply allow the command to take -10 as a valid value again?

**Comment by Whurrhurr** [comment]
> > mat_picmip now can go lower than -1 so i guess you can close this issue.
> 
> Depends, does being allowed to set mat_picmip below -1 also imply that the textures are indeed "cleaned" as proposed above, or did they simply allow the command to take -10 as a valid value again?

they simply let you use mat_picmip -10 now.

**Comment by agrastiOs** [comment]
Obsolete as mat_picmip -10 can now be set in-game.
