### ISSUE TITLE
Map fixes

### ISSUE THREAD

**Issue by MikhailaTF** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#35]
Originally I planned on opening an issue related to bad poor lighting on older maps, but as I went through the different maps to screenshots of said  bad lighting I have come across countless issues.

Most notably is indeed the bad lighting (blocky shadows, parts of the map and props being either full bright or too dark, artifacts, inconstant lighting,....) which is very prominent on most of the older maps but I've found that such instances can be found to a lesser extend on just about any official map. Makes me wonder if there could be some sort of streamlined high-quality standard for compiling the lighting on official maps (lighting on other source-based games' maps can look crisp, why wouldn't it in TF2 as well?). I would provide screenshots but the folder i have is just too big, opening up any map (especially the older ones) and looking around for a bit or inspecting props will quickly reveal what I'm talking about.

While on my quest for screenshots for the aforementioned issue I've also come across a few other miscellaneous visual issues on certain maps.

On cp_well, the logo on the main building of team RED is missing. I assume it is missing because said logo is present on ctf_well. I make no claims about a logo on the main building of team BLU as there's none on either map (although it may just as well be missing from both versions).

![cp_well logo RED (missing)](https://user-images.githubusercontent.com/71837773/98984813-feddda00-2522-11eb-942f-885d3a92127d.jpg)
cp_well: logo is missing
![ctf_well RED logo (present)](https://user-images.githubusercontent.com/71837773/98984856-09986f00-2523-11eb-82ed-d44211ebdd97.jpg)
ctf_well: logo is present

I have also come across a pixel-wide gap on ctf_well
![ctf_well pixel-wide gap](https://user-images.githubusercontent.com/71837773/98985046-4d8b7400-2523-11eb-8d56-648757b12c46.jpg)
ctf_well: pixel-wide gap near 1 of RED's spawns

Furthermore, there seems to be a missing some geometry on the main stairs of ctf_turbine on both sides
![ctf_turbine gap in stairs on BLU 1](https://user-images.githubusercontent.com/71837773/98985262-993e1d80-2523-11eb-906d-b4c71ff62ba9.jpg)
ctf_turbine: issue with the stairs on BLU's side
![ctf_turbine gap in stairs on BLU 2](https://user-images.githubusercontent.com/71837773/98985266-9a6f4a80-2523-11eb-98cb-34a178fc38ec.jpg)
ctf_turbine: issue with the stairs on BLU's side
![ctf_turbine gap in stairs RED](https://user-images.githubusercontent.com/71837773/98985315-ab1fc080-2523-11eb-9c4e-862a0ac06b7e.jpg)
ctf_turbine: issue with the stairs on RED's side
![ctf_turbine how stairs should be](https://user-images.githubusercontent.com/71837773/98985330-afe47480-2523-11eb-9d91-681d87971e52.jpg)
ctf_turbine: interestingly enough, this other side of the stairs on RED's side are fine, immediately giving an idea of what the rest is supposed to look like.

And at last, I have also found the tiniest stripe of RED paint on an otherwise BLU-colored bit of the map on ctf_doublecross.
![ctf_doublecross red bit on BLU side 1](https://user-images.githubusercontent.com/71837773/98985514-f0dc8900-2523-11eb-9c82-bea0cb19464b.jpg)
ctf_turbine: that paint is a spy!

Note 1: I was told that one needs strict permissions from the respective creators of any map to be able to make any changes, so if that is true than I doubt anything I've said here can be fixed within the scope of this pack, aw chucks!
Note 2: I've only really gone and check maps up to cp_steel (starting from the oldest maps up to the update this one was added). If indeed these fixes could be applied within this pack, I'd happily set my eyes from some more to find other such miscellaneous issues in official maps.

**Comment by PoorPocketsMcNewHold** [comment]
I suppose most of these issues, would need to be modified and recompiled as a map itself. And trying to modify a vanilla map file, will result into being denied access when playing a server, due to the different map.

[(And the method of preloading some edited map assets previously was patched as well)](https://youtu.be/oQJ8-_IJO5s)

What i would suggest you,  is to either, potentially propose to make a modified map with fixes (A lot of ¨pro¨ competitive edits also contains some overhaul map fixes like these if they doesn’t derive from the gameplay) and, to propose it to server owner who would host that modified map instead.

[And another thing, would be to propose those changes to the team-comtress-2](https://github.com/mastercomfig/team-comtress-2), which is a fork of Team Fortress 2 derived from leaked source code, which aim to provide a more optimized, and fixed, Team Fortress 2 game while waiting for official endorsement. I don’t know if they directly allow suggesting map edits, but this would very likely be beneficial for them.

**Comment by agrastiOs** [comment]
^ What PoorPocketsMcNewHold said.

Map fixes would be hugely out of this project's scope, considering the fact that we don't have the original map files for these maps. The only way we could edit the maps is by decompiling, which is not the same as editing the source file, and I really doubt Valve would accept the updated versions of a map that were made by decompiling it. Your best bet is to ask the map author (Valve too if they are the map authors) to fix the issues.

Closing.
