### ISSUE TITLE
Illumination inconsistencies on flame throwers

### ISSUE THREAD

**Issue by MikhailaTF** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#36]
It's always been apparent to me that the flames from the Dragon's Fury, unlike the flames from the other flame throwers, has the property of illumination.

![illumination dragon's fury](https://user-images.githubusercontent.com/71837773/99877345-ded2a880-2bfd-11eb-91eb-b9d862232754.gif)
Dragon's fury flames

![illumination flame thrower](https://user-images.githubusercontent.com/71837773/99877349-e1350280-2bfd-11eb-80f3-4e9872724f29.gif)
regular Flame Thrower (also holds true for the Backburner and the Degreaser)

I understand that many things in TF2 could have the property of illumination (Unusuals, festive lights, certain cosmetics, all flame throwers) but don't because of visual clarity and performance. I also understand why these 2 arguments are less of an issue for just the Dragon's Fury, but it just feels inconsistent and out of place.

If there is one such case I do think deserves such properties instead, it is the light atop of the Mini-Sentry. Even though there's clearly a light mounted on top of it, the "light" is just a sprite and not a very good one at that.

![illumination mini-sentry](https://user-images.githubusercontent.com/71837773/99877354-e4c88980-2bfd-11eb-9a24-4eb6a5d48685.gif)
Mini-Sentry's "light"

I understand this last suggestion is more subjective than anything else, but then again so is this entire post to a certain degree.

**Comment by agrastiOs** [comment]
The illumination of the DF projectile is entirely code based: the projectile is regarded as an entity type which has the client-side glow.
