### ISSUE TITLE
i dont know where i should put this but i put it here

### ISSUE THREAD

**Issue by 69420-cell** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#38]
so i wanted to know if you can make a version of this pack that is compatible with valve servers (i know that a lot of the fixes cant be compatible with valve servers but i'm asking if you can do a version with the things that can be done like the reduction of the fire particles, extended dragun fury fire that kind of stuff)

**Comment by PoorPocketsMcNewHold** [comment]
Won’t help. If certain parts of the mod will be blocked by the sv\_pure settings, it’s useless to make a version without them.

Other parts of the mod who work under sv\_pure settings, will work just fine.

[_BTW, I’ll suggest that you take a look at the creators.tf servers as an alternative of playing on the Valve servers, if you weren’t playing it for the competitive mode or the vanilla MvM campaign._](https://creators.tf)

**Comment by agrastiOs** [comment]
Closing for the reasons that PoorPocketsMcNewHold has mentioned.

Like they have also mentioned, try out the creators.tf servers, which also include an easy way to install the pack from their launcher.
