### ISSUE TITLE
Game stutters with this pack

### ISSUE THREAD

**Issue by deni294** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#4]
When I have this pack installed, the game briefly stutters upon switching to a weapon with a war paint on it. This only happens when I switch to said weapon for the first time. Is there any way around this?

**Comment by agrastiOs** [comment]
Interesting... Are you sure it doesn't happen too with vanilla?

**Comment by deni294** [comment]
Without the pack installed, switching to war painted weapons doesn't stutter the game. Although it seems to take roughly 0.25 - 0.5 seconds to load the skin, it doesn't lag the game.

But with the pack installed, the game stutters upon switching to a skinned weapon. On normal, non-skinned weapons, it's fine.

**Comment by agrastiOs** [comment]
Does it happen on every single war painted weapon you have? Does it happen on the skinned weapons before Jungle Inferno?

**Comment by deni294** [comment]
Sorry for the delayed response. I tested this again, this time with a clean install of TF2. My game stutters upon switching to any skinned weapon for the first time, even pre-Jungle Inferno skins. Switching back to a skinned weapon I switched to before does not cause any lag.

I ruled out that this shader fix is not the cause of the lag, therefore I will be closing this issue.
