### ISSUE TITLE
Demoman Primary Fixes

### ISSUE THREAD

**Issue by ItsVladGames** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#42]
Please fix the Demo Primary Reload, the Default one was made for only Stock, and it is just off with any other Grenade Launcher, maybe except the Loch-n-Load. It would also help adding a Battle Spin to Stock and the Iron Bomber when shooting and reloading if Possible. And center the Loose Cannon Pipes, so that they actually enter the chamber. Thanks.

**Comment by agrastiOs** [comment]
Duplicate of #18, I suggest that you add several ideas that are missing from there in that particular issue.
