### ISSUE TITLE
[Bug] c_sandwich_xmas and c_sandwich_xmas_blue do not remove their crit/minicrit glow after being crit/minicrit boosted

### ISSUE THREAD

**Issue by Whurrhurr** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#43]
when crit boosted: 
![image](https://user-images.githubusercontent.com/33162051/104935353-fad59a80-595f-11eb-9522-6fed6626f7ed.png)
when no longer crit boosted: 
![image](https://user-images.githubusercontent.com/33162051/104935395-05902f80-5960-11eb-9c0f-702e655045e5.png)

**Comment by agrastiOs** [comment]
Requested to upload on GitHub.

Thank you again for the fixes.
