### ISSUE TITLE
Patch manmelter visual bugs and make the vacuum and spark more visible.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#48]
As it stands there is at least one bug with the manmelter (a random flame appearing when firing a crit flare) and the manmelter spark and vacuum, as most people have stated, are very difficult to actually see and notice.

**Comment by NonhumanFromSteam** [comment]
**Manmelter now has a flash indicator when it's ready to fire and the idle spark is more visible**, however the vacuum not appearing consistently seems to be an issue unrelated to particles and is a core code based issue and cannot be fixed in this pack.
