### ISSUE TITLE
Creators.tf

### ISSUE THREAD

**Issue by donull** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#5]
Wondering if you're considering sending this to the creators.tf project? Would be really great if you did!

**Comment by agrastiOs** [comment]
Hmmm, sounds interesting. Thank you for reminding me of the website. I'll make sure to look into it sometime.

**Comment by agrastiOs** [comment]
@donull The Pack is now officially included with the Creators.TF Launcher! 
https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/tag/v0.2.0
