### ISSUE TITLE
Sniper rifle skins are incorrectly applied to scope

### ISSUE THREAD

**Issue by Tkain** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#50]
When a skinned Sniper Rifle is used, the Sniper Rifle's texture is incorrectly applied to the scope of the rifle. 
See the images below for reference: 

**Without UTF2VFP installed:**

![Without pack (correct)](https://user-images.githubusercontent.com/8422056/123527625-0cf5fa80-d6af-11eb-8299-fb560371343e.jpg)

**With UTF2VFP installed:**

![With pack (incorrect)](https://user-images.githubusercontent.com/8422056/123527624-0cf5fa80-d6af-11eb-88de-187b4615bade.jpg)

What I think is happening is that TF2 is replacing the sniper rifle scope's texture with that of the skinned sniper rifle's body because it only expects the rifle to use one texture, resulting in incorrect UV mappings. Interestingly, however, the scope seems to keep its shine, hinting that it might be keeping its material properties.

So, what I propose is to make the sniper rifle scope's material use the right part of the sniper rifle body's texture, just like it does in live TF2, alongside its custom material properties. That way, when the textures get replaced, the scope looks like it usually does.

**Comment by agrastiOs** [comment]
That's actually a great idea! Closing as duplicate, please add this post to #25.
