### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by AtomicTEM** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#6]
just checking. Also, could you make the jumper effects a sperate mod? Please.

**Comment by agrastiOs** [comment]
Yep, still going on, just we're all taking a break.
Final release is planned to have several VPKs for each part of the pack.

**Comment by AtomicTEM** [comment]
Cool.

**Comment by AtomicTEM** [comment]
Also, you guys are doing great work Thank you.

**Comment by agrastiOs** [comment]
Cheers.
