### ISSUE TITLE
Voodoo-Cursed Souls don't have rimlights

### ISSUE THREAD

**Issue by Ashetf2** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#60]
https://github.com/ValveSoftware/Source-1-Games/issues/3703

**Comment by Tkain** [comment]
A mod on Gamebanana, ["Consistent Voodoo-cursed soul VMTs"](https://gamebanana.com/mods/346110), fixes this.

**Comment by Whurrhurr** [comment]
i know i sent agrastiOs the consistent zombie vmts before i uploaded them to gamebanana, my only guess is he forgot to add them to the visual fix pack

**Comment by agrastiOs** [comment]
Fixed.

Thanks to Whurr for the report and proposed fix!
