### ISSUE TITLE
Bugged glasses on Honcho's Headgear and Ground Control

### ISSUE THREAD

**Issue by Rongeno** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#62]
So there is a problen with glasses on Honcho's Headgear and Ground Control that from certian angles the visors do not appear.
![NyWczYR](https://user-images.githubusercontent.com/108897156/177855955-716b12d3-cf33-414b-9014-b8ada5123a00.jpeg)
![20220707222338_1](https://user-images.githubusercontent.com/108897156/177855966-21c7d63d-21f7-42ac-9f78-b3536061eead.jpg)

**Comment by agrastiOs** [comment]
Fixed in latest patch.
