### ISSUE TITLE
Sometimes Overwrites Mods

### ISSUE THREAD

**Issue by floofycatto** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#64]
Hi! So I was tryna install a pretty popular mod, basically the [toon explosions fx mod](https://gamebanana.com/mods/12446) and i noticed that mod didnt work, and i was thinking this mod might've been the issue, turns out i was correct, dont know if anything could be done to fix this via here, but that would be cool

**Comment by agrastiOs** [comment]
TF2 loads mods in alphanumeric order. If you want the Toon Explosions FX mod to work and overwrite the Visual Fix Pack, when installing both mods, you can add A or 1 to the Visual Fix Pack .vpk names. (So like AUltimateVisualFix_dir.vpk)

**Comment by agrastiOs** [comment]
As the question was answered, I'll close the issue. Feel free to reopen if needed
