### ISSUE TITLE
Ultimate Visual Pack Overwrites Other Mods

### ISSUE THREAD

**Issue by floofycatto** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#69]
I seem to have noticed while installing other mods alongside this it seems to overwrite them, here's some that I ran into

- Cartoon Explosives Mod
- Cartoon Projectiles Mod

I guess it seems to mostly be effects that are being overlapped
since this pack is mostly focused on improving vanilla Team Fortress 2 visuals, people obviously install other mods to make their game look different, and I don't really think they would want a vanilla looking mod to overwrite whatever mod they have installed

is there any way you could fix this? Thanks for reading

**Comment by agrastiOs** [comment]
TF2 loads mods in alphanumeric order. If you want the Toon Explosions FX mod to work and overwrite the Visual Fix Pack, when installing both mods, you can add A or 1 to the Visual Fix Pack .vpk names. (So like AUltimateVisualFix_dir.vpk)

**Comment by agrastiOs** [comment]
Copied from #64.

**Comment by floofycatto** [comment]
> TF2 loads mods in alphanumeric order. If you want the Toon Explosions FX mod to work and overwrite the Visual Fix Pack, when installing both mods, you can add A or 1 to the Visual Fix Pack .vpk names. (So like AUltimateVisualFix_dir.vpk)

thanks for the reply! I'll try it out

**Comment by floofycatto** [comment]
Hey! Back here with the results, it's a really interesting situation

so I added a 1_ before the mod, the file name is now 1_toon_explosives_v1.1.vpk

the first time did not work, and was overrided with the new visual fix textures

I thought since Ultimate Visual Pack Fix was in a folder, I would also put the explosions mod in their own folder, so I did that

opened up a custom server, with sv_pure 0 on, made sure cloud save was up to date, and the results were the same, no cartoon explosions

but the interesting part about it is I also put a 1 before the cartoon projectiles mod, and that worked just fine and didn't get overrid like how it did before

possible solution i see to this is putting the ultimate visual pack fix into a vpk, because maybe there's something in the custom folder loading before the explosives mod

tf2 code is weird lol

**Comment by floofycatto** [comment]
sorry i didnt see this, apologies for that, I thought the issue I posted didnt go through for some reason
