### ISSUE TITLE
Improved Default Cubemap

### ISSUE THREAD

**Issue by floofycatto** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#74]
Hello! Another suggestion to add to this fix pack!

Someone on gamebanana has ported the Gmod improved default cubemap to Team Fortress 2

gmod link: https://steamcommunity.com/sharedfiles/filedetails/?id=2713425690&searchtext=
![image](https://user-images.githubusercontent.com/86273332/221624880-d38bcf85-7259-4e3d-ae20-a738c236ed1a.png)

In gmod you can see that some things glow way too bright, also if you look on the workshop you can see more before and afters, whats most noticable is you have this ugly, dirty "golden" reflection coming off of metal objects, which doesn't really fit well with the map, and this "improved" one looks more accurate to how a metal object would actually reflect something, this same issue seems to translate to Team Fortress 2, which is why I believe it should be included in this visual fix pack

gamebanana tf2 link: https://gamebanana.com/mods/397448
![image](https://user-images.githubusercontent.com/86273332/221625656-a15ceda2-335c-4aa4-8820-d6ffa3afec41.png)

**Comment by PoorPocketsMcNewHold** [comment]
> A consistency pass for both stock and non-stock: the few weapons which had the ugly (particularly in darker environments or places with bright cube map) environmental cube map applied have been fixed, glass for all weapons is now more or less consistent.
That’s to see if it didn’t had an altered cubemap already.
